version: "3.3"

services:
  backend:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    environment:
      CONFIG_PATH: /app/configs/config.toml
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src:ro
      - ../src/infra/postgres/migration/versions:/app/src/infra/postgres/migration/versions:rw
    depends_on:
      - database

  database:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.co
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

  keycloak-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HTTPS: "disabled"     
    command:
      - start-dev
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db


volumes:
  keycloak_db_data:
